// Mocks generated by Mockito 5.4.6 from annotations
// in larvixon_frontend/test/src/user/bloc/cubit/user_edit_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i8;

import 'package:fpdart/fpdart.dart' as _i5;
import 'package:larvixon_frontend/core/errors/failures.dart' as _i6;
import 'package:larvixon_frontend/src/user/domain/entities/user.dart' as _i4;
import 'package:larvixon_frontend/src/user/domain/repositories/user_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.User> get userStream =>
      (super.noSuchMethod(
            Invocation.getter(#userStream),
            returnValue: _i3.Stream<_i4.User>.empty(),
          )
          as _i3.Stream<_i4.User>);

  @override
  _i5.TaskEither<_i6.Failure, _i4.User> fetchUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, []),
            returnValue: _i7.dummyValue<_i5.TaskEither<_i6.Failure, _i4.User>>(
              this,
              Invocation.method(#fetchUserProfile, []),
            ),
          )
          as _i5.TaskEither<_i6.Failure, _i4.User>);

  @override
  _i5.TaskEither<_i6.Failure, void> updateUserProfileDetails({
    String? phoneNumber,
    String? bio,
    String? org,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfileDetails, [], {
              #phoneNumber: phoneNumber,
              #bio: bio,
              #org: org,
            }),
            returnValue: _i7.dummyValue<_i5.TaskEither<_i6.Failure, void>>(
              this,
              Invocation.method(#updateUserProfileDetails, [], {
                #phoneNumber: phoneNumber,
                #bio: bio,
                #org: org,
              }),
            ),
          )
          as _i5.TaskEither<_i6.Failure, void>);

  @override
  _i5.TaskEither<_i6.Failure, void> updateUserProfileBasicInfo({
    required String? firstName,
    required String? lastName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfileBasicInfo, [], {
              #firstName: firstName,
              #lastName: lastName,
            }),
            returnValue: _i7.dummyValue<_i5.TaskEither<_i6.Failure, void>>(
              this,
              Invocation.method(#updateUserProfileBasicInfo, [], {
                #firstName: firstName,
                #lastName: lastName,
              }),
            ),
          )
          as _i5.TaskEither<_i6.Failure, void>);

  @override
  _i5.TaskEither<_i6.Failure, void> updateUserProfilePhoto({
    required _i8.Uint8List? bytes,
    required String? fileName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfilePhoto, [], {
              #bytes: bytes,
              #fileName: fileName,
            }),
            returnValue: _i7.dummyValue<_i5.TaskEither<_i6.Failure, void>>(
              this,
              Invocation.method(#updateUserProfilePhoto, [], {
                #bytes: bytes,
                #fileName: fileName,
              }),
            ),
          )
          as _i5.TaskEither<_i6.Failure, void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
