// Mocks generated by Mockito 5.4.6 from annotations
// in larvixon_frontend/test/src/user/domain/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:larvixon_frontend/core/api_client.dart' as _i2;
import 'package:larvixon_frontend/src/user/data/models/user_dto.dart' as _i3;
import 'package:larvixon_frontend/src/user/data/user_datasource.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfileDTO_1 extends _i1.SmartFake
    implements _i3.UserProfileDTO {
  _FakeUserProfileDTO_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfileDetailsDTO_2 extends _i1.SmartFake
    implements _i3.UserProfileDetailsDTO {
  _FakeUserProfileDetailsDTO_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataSource extends _i1.Mock implements _i4.UserDataSource {
  MockUserDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i5.Future<_i3.UserProfileDTO> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i5.Future<_i3.UserProfileDTO>.value(
              _FakeUserProfileDTO_1(
                this,
                Invocation.method(#getUserProfile, []),
              ),
            ),
          )
          as _i5.Future<_i3.UserProfileDTO>);

  @override
  _i5.Future<_i3.UserProfileDTO> updateUserProfile({
    required _i3.UserProfileDTO? dto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {#dto: dto}),
            returnValue: _i5.Future<_i3.UserProfileDTO>.value(
              _FakeUserProfileDTO_1(
                this,
                Invocation.method(#updateUserProfile, [], {#dto: dto}),
              ),
            ),
          )
          as _i5.Future<_i3.UserProfileDTO>);

  @override
  _i5.Future<void> updateUserProfilePhoto({
    required _i6.Uint8List? bytes,
    required String? fileName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfilePhoto, [], {
              #bytes: bytes,
              #fileName: fileName,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserProfileDetailsDTO> updateUserProfileDetails({
    required _i3.UserProfileDetailsDTO? profileDetails,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfileDetails, [], {
              #profileDetails: profileDetails,
            }),
            returnValue: _i5.Future<_i3.UserProfileDetailsDTO>.value(
              _FakeUserProfileDetailsDTO_2(
                this,
                Invocation.method(#updateUserProfileDetails, [], {
                  #profileDetails: profileDetails,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.UserProfileDetailsDTO>);
}
