// Mocks generated by Mockito 5.4.6 from annotations
// in larvixon_frontend/test/src/user/presentation/widgets/details_section_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:bloc/bloc.dart' as _i6;
import 'package:larvixon_frontend/src/user/bloc/cubit/user_edit_cubit.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserEditCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserEditCubit extends _i1.Mock implements _i2.UserEditCubit {
  MockUserEditCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserEditState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i3.dummyValue<_i2.UserEditState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.UserEditState);

  @override
  _i4.Stream<_i2.UserEditState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.UserEditState>.empty(),
          )
          as _i4.Stream<_i2.UserEditState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i4.Future<void> updateDetails({
    String? phoneNumber,
    String? bio,
    String? organization,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDetails, [], {
              #phoneNumber: phoneNumber,
              #bio: bio,
              #organization: organization,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateBasicInfo({
    required String? firstName,
    required String? lastName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBasicInfo, [], {
              #firstName: firstName,
              #lastName: lastName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePhoto({
    required _i5.Uint8List? bytes,
    required String? fileName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoto, [], {
              #bytes: bytes,
              #fileName: fileName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void emit(_i2.UserEditState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i6.Change<_i2.UserEditState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
