include: package:flutter_lints/flutter.yaml
linter:
  rules:      
    prefer_const_constructors: true  
    prefer_const_declarations: true 
    prefer_const_literals_to_create_immutables: true 
    always_declare_return_types: true
    avoid_print: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    avoid_redundant_argument_values: true
    unnecessary_this: true
    prefer_const_constructors_in_immutables: true
    avoid_unnecessary_containers: true
    avoid_types_as_parameter_names: true
    await_only_futures: true
    cancel_subscriptions: true
    close_sinks: true
    require_trailing_commas: true
    use_build_context_synchronously: false 
    omit_local_variable_types: false
    avoid_dynamic_calls: true
    always_use_package_imports: true
