// Mocks generated by Mockito 5.4.6 from annotations
// in larvixon_frontend/test/src/analysis/blocs/analysis_bloc/analysis_bloc_retry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i13;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:larvixon_frontend/core/errors/failures.dart' as _i6;
import 'package:larvixon_frontend/src/analysis/domain/entities/analysis.dart'
    as _i10;
import 'package:larvixon_frontend/src/analysis/domain/entities/analysis_filter.dart'
    as _i8;
import 'package:larvixon_frontend/src/analysis/domain/entities/analysis_id_list.dart'
    as _i4;
import 'package:larvixon_frontend/src/analysis/domain/entities/analysis_sort.dart'
    as _i7;
import 'package:larvixon_frontend/src/analysis/domain/entities/analysis_upload_response.dart'
    as _i11;
import 'package:larvixon_frontend/src/analysis/domain/repositories/analysis_repository.dart'
    as _i2;
import 'package:larvixon_frontend/src/common/services/file_picker/file_pick_result.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AnalysisRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalysisRepository extends _i1.Mock
    implements _i2.AnalysisRepository {
  MockAnalysisRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.AnalysisIdList> get analysisIdsStream =>
      (super.noSuchMethod(
            Invocation.getter(#analysisIdsStream),
            returnValue: _i3.Stream<_i4.AnalysisIdList>.empty(),
          )
          as _i3.Stream<_i4.AnalysisIdList>);

  @override
  _i3.Stream<int> get analysisUpdatesStream =>
      (super.noSuchMethod(
            Invocation.getter(#analysisUpdatesStream),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i5.TaskEither<_i6.Failure, _i4.AnalysisIdList> fetchVideoIds({
    String? nextPage,
    _i7.AnalysisSort? sort,
    _i8.AnalysisFilter? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchVideoIds, [], {
              #nextPage: nextPage,
              #sort: sort,
              #filter: filter,
            }),
            returnValue: _i9
                .dummyValue<_i5.TaskEither<_i6.Failure, _i4.AnalysisIdList>>(
                  this,
                  Invocation.method(#fetchVideoIds, [], {
                    #nextPage: nextPage,
                    #sort: sort,
                    #filter: filter,
                  }),
                ),
          )
          as _i5.TaskEither<_i6.Failure, _i4.AnalysisIdList>);

  @override
  _i5.TaskEither<_i6.Failure, _i10.Analysis> fetchVideoDetailsById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchVideoDetailsById, [id]),
            returnValue: _i9
                .dummyValue<_i5.TaskEither<_i6.Failure, _i10.Analysis>>(
                  this,
                  Invocation.method(#fetchVideoDetailsById, [id]),
                ),
          )
          as _i5.TaskEither<_i6.Failure, _i10.Analysis>);

  @override
  _i3.Future<List<_i10.Analysis>> fetchVideosDetails() =>
      (super.noSuchMethod(
            Invocation.method(#fetchVideosDetails, []),
            returnValue: _i3.Future<List<_i10.Analysis>>.value(
              <_i10.Analysis>[],
            ),
          )
          as _i3.Future<List<_i10.Analysis>>);

  @override
  _i3.Stream<_i5.Either<_i6.Failure, _i10.Analysis>> watchVideoProgressById({
    required int? id,
    Duration? interval = const Duration(seconds: 5),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchVideoProgressById, [], {
              #id: id,
              #interval: interval,
            }),
            returnValue:
                _i3.Stream<_i5.Either<_i6.Failure, _i10.Analysis>>.empty(),
          )
          as _i3.Stream<_i5.Either<_i6.Failure, _i10.Analysis>>);

  @override
  _i5.TaskEither<_i6.Failure, _i11.AnalysisUploadResponse> uploadVideo({
    required _i12.FilePickResult? fileResult,
    String? description,
    void Function(double)? onProgress,
    _i13.CancelToken? cancelToken,
    String? patientId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadVideo, [], {
              #fileResult: fileResult,
              #description: description,
              #onProgress: onProgress,
              #cancelToken: cancelToken,
              #patientId: patientId,
            }),
            returnValue: _i9
                .dummyValue<
                  _i5.TaskEither<_i6.Failure, _i11.AnalysisUploadResponse>
                >(
                  this,
                  Invocation.method(#uploadVideo, [], {
                    #fileResult: fileResult,
                    #description: description,
                    #onProgress: onProgress,
                    #cancelToken: cancelToken,
                    #patientId: patientId,
                  }),
                ),
          )
          as _i5.TaskEither<_i6.Failure, _i11.AnalysisUploadResponse>);

  @override
  _i5.TaskEither<_i6.Failure, bool> deleteAnalysis({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAnalysis, [], {#id: id}),
            returnValue: _i9.dummyValue<_i5.TaskEither<_i6.Failure, bool>>(
              this,
              Invocation.method(#deleteAnalysis, [], {#id: id}),
            ),
          )
          as _i5.TaskEither<_i6.Failure, bool>);

  @override
  _i5.TaskEither<_i6.Failure, _i10.Analysis> retryAnalysis({
    required int? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#retryAnalysis, [], {#id: id}),
            returnValue: _i9
                .dummyValue<_i5.TaskEither<_i6.Failure, _i10.Analysis>>(
                  this,
                  Invocation.method(#retryAnalysis, [], {#id: id}),
                ),
          )
          as _i5.TaskEither<_i6.Failure, _i10.Analysis>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
