// Mocks generated by Mockito 5.4.6 from annotations
// in larvixon_frontend/test/src/authentication/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:fpdart/fpdart.dart' as _i3;
import 'package:larvixon_frontend/core/errors/failures.dart' as _i4;
import 'package:larvixon_frontend/src/authentication/bloc/auth_bloc.dart'
    as _i6;
import 'package:larvixon_frontend/src/authentication/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TaskEither<_i4.Failure, void> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i5.dummyValue<_i3.TaskEither<_i4.Failure, void>>(
              this,
              Invocation.method(#login, [], {
                #email: email,
                #password: password,
              }),
            ),
          )
          as _i3.TaskEither<_i4.Failure, void>);

  @override
  _i3.TaskEither<_i4.Failure, void> register({
    required String? username,
    required String? email,
    required String? password,
    required String? passwordConfirm,
    required String? firstName,
    required String? lastName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #username: username,
              #email: email,
              #password: password,
              #passwordConfirm: passwordConfirm,
              #firstName: firstName,
              #lastName: lastName,
            }),
            returnValue: _i5.dummyValue<_i3.TaskEither<_i4.Failure, void>>(
              this,
              Invocation.method(#register, [], {
                #username: username,
                #email: email,
                #password: password,
                #passwordConfirm: passwordConfirm,
                #firstName: firstName,
                #lastName: lastName,
              }),
            ),
          )
          as _i3.TaskEither<_i4.Failure, void>);

  @override
  _i3.TaskEither<_i4.Failure, void> refreshTokens() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, []),
            returnValue: _i5.dummyValue<_i3.TaskEither<_i4.Failure, void>>(
              this,
              Invocation.method(#refreshTokens, []),
            ),
          )
          as _i3.TaskEither<_i4.Failure, void>);

  @override
  _i3.TaskEither<_i4.Failure, void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.dummyValue<_i3.TaskEither<_i4.Failure, void>>(
              this,
              Invocation.method(#logout, []),
            ),
          )
          as _i3.TaskEither<_i4.Failure, void>);

  @override
  _i3.TaskEither<_i4.Failure, _i6.AuthStatus> checkAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthStatus, []),
            returnValue: _i5
                .dummyValue<_i3.TaskEither<_i4.Failure, _i6.AuthStatus>>(
                  this,
                  Invocation.method(#checkAuthStatus, []),
                ),
          )
          as _i3.TaskEither<_i4.Failure, _i6.AuthStatus>);

  @override
  _i3.TaskEither<_i4.Failure, bool> hasValidToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasValidToken, []),
            returnValue: _i5.dummyValue<_i3.TaskEither<_i4.Failure, bool>>(
              this,
              Invocation.method(#hasValidToken, []),
            ),
          )
          as _i3.TaskEither<_i4.Failure, bool>);

  @override
  _i3.TaskEither<_i4.Failure, bool> verifyToken() =>
      (super.noSuchMethod(
            Invocation.method(#verifyToken, []),
            returnValue: _i5.dummyValue<_i3.TaskEither<_i4.Failure, bool>>(
              this,
              Invocation.method(#verifyToken, []),
            ),
          )
          as _i3.TaskEither<_i4.Failure, bool>);
}
